pipeline:
  stages:
    - name: Lint & Validate
      steps:
        - name: Lint YAML Files
          image: mikefarah/yq
          script:
            - yq e '.' k8s/**/*.yaml > /dev/null
        - name: Validate Kustomize
          image: bitnami/kubectl
          script:
            - kubectl kustomize k8s/base > /dev/null
            - kubectl kustomize k8s/overlays/dev > /dev/null
            - kubectl kustomize k8s/overlays/staging > /dev/null
            - kubectl kustomize k8s/overlays/production > /dev/null

    - name: Deploy to Dev
      if: branch == 'dev'
      steps:
        - name: Deploy Dev Environment
          image: bitnami/kubectl
          script:
            - kubectl apply -k k8s/overlays/dev

    - name: Deploy to Staging
      if: branch == 'stg'
      steps:
        - name: Deploy Staging Environment
          image: bitnami/kubectl
          script:
            - kubectl apply -k k8s/overlays/staging

    - name: Deploy to Production
      if: branch == 'main'
      steps:
        - name: Deploy Production Environment
          image: bitnami/kubectl
          script:
            - kubectl apply -k k8s/overlays/production
