apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-service-dev
  namespace: default
spec:
  project: web-app-dev
  source:
    repoURL: 'https://github.com/lucasrestrepo/kargo.git'
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
