apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-service-production
  namespace: default
spec:
  project: web-app-prd
  source:
    repoURL: 'https://github.com/lucasrestrepo/kargo.git'  # Replace with your repository URL
    targetRevision: HEAD
    path: k8s/overlays/prd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
