name: Kargo CI/CD Pipeline for GKE with Kustomize

on:
  push:
    branches:
      - main
      - dev
      - stg

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ${{ secrets.GKE_KUBECONFIG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.GKE_KUBECONFIG }}" > ~/.kube/config

      - name: Install Kargo
        run: |
          curl -Lo kargo "https://github.com/mumoshu/kargo/releases/download/v0.1.0/kargo-linux-amd64"
          chmod +x kargo
          sudo mv kargo /usr/local/bin/kargo

      - name: test Kargo
        run: |    
          kargo --version
          ls -lr /usr/local/bin/kargo
          
      - name: Deploy to GKE with Kargo
        run: |
          # Determine environment and apply kustomize overlay
          if [ "${GITHUB_REF##*/}" == "main" ]; then
            kargo -f kargo.yaml apply production
          elif [ "${GITHUB_REF##*/}" == "stg" ]; then
            kargo -f kargo.yaml apply staging
          elif [ "${GITHUB_REF##*/}" == "dev" ]; then
            kargo -f kargo.yaml apply dev
          else
            echo "No matching environment for branch ${GITHUB_REF##*/}"
          fi
