name: Kargo CI/CD Pipeline for GKE

on:
  push:
    branches:
      - main
      - dev
      - stg

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ${{ secrets.GKE_KUBECONFIG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.GKE_KUBECONFIG }}" > ~/.kube/config

      - name: Download and Install Kargo
        run: |
          # Download Kargo binary
          curl -Lo kargo "https://github.com/kargo-ci/kargo/releases/download/v0.2.0/kargo-linux-amd64"
          # Make sure the file is executable
          chmod +x kargo
          # Move it to a directory in the PATH
          sudo mv kargo /usr/local/bin/kargo
          # Verify that Kargo is installed
          kargo --version

      - name: Run Kargo Pipeline
        run: kargo


